### ISSUE TITLE
Automtizar publish para o npm com o gh actions

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#1]

**Comment by welksonramos** [comment]
Você pode usar esta action https://github.com/pascalgn/npm-publish-action

**Comment by victorperin** [comment]
Senhores, alguem está trabalhando nisso? Posso ajudar com um pull request?

Estou pensando em ajudar durante esse final de semana.

**Comment by lucaspompeun** [comment]
Olá, @victorperin. Ainda não começamos a trabalhar nisso, mas você pode nos ajudar sim :)

**Comment by carapires** [comment]
pull request

**Comment by lucaspompeun** [comment]
Automação implementada, pessoal.
Agradeço as ideia e considerações :D
