### ISSUE TITLE
escreva(verdadeiro) em console retorna "true"

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [eguatech/egua#100]
Passos para execução:

1. Instalar o interpretador usando `npm` ou `yarn`;
2. Abrir um prompt e executar `egua`
3. Com o prompt do Egua, executar o seguinte:

```
egua> escreva(verdadeiro);
true

egua> escreva(verdadeiro e falso);
false

egua> escreva(verdadeiro ou falso);
true
```

Entendo que deveria retornar "verdadeiro", "falso" e "verdadeiro", não?

**Comment by lucaspompeun** [comment]
Correto. Esse é o comportamento esperado. Podemos corrigir esse comportamento

**Comment by leonelsanchesdasilva** [comment]
Eu vou discordar. Se estamos indo para uma linguagem 100% em português, os valores devem ser em português.

Imagino que o objetivo seja ser acessível para pessoas cujo único idioma é o português. Elas não sabem o que é "true" e "false".

**Comment by lucaspompeun** [comment]
Eu concordei com você. Respondi referente a pergunta "Entendo que deveria retornar "verdadeiro", "falso" e "verdadeiro", não?"

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva precisei desfazer o PR devido a ele ir direto para a master, você poderia reabrir ele apontando a alteração para desenvolvimento?

**Comment by leonelsanchesdasilva** [comment]
Creio que este bug possa ser fechado agora.
