### ISSUE TITLE
tempo.horario() não faz sentido

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [eguatech/egua#116]
`tempo.horario(timestamp)` tem uma série de problemas:

- O nome não condiz com o que a função faz (transformar um texto no formato DD/MM/AAAA em uma variável de data à meia-noite);
- Ainda que seja uma função para transformar texto em data, os formatos a serem considerados [devem ser compatíveis com todos esses países](https://en.wikipedia.org/wiki/List_of_countries_and_territories_where_Portuguese_is_an_official_language), e não apenas o Brasil;
- A variável `timestamp` claramente não é um carimbo de tempo (tradução literal), é um texto que representa uma data.

Minha sugestão:

- Mudar o nome da função para `textoParaData()`;
- Mudar o nome do parâmetro para `dataComoTexto`.

**Comment by lucaspompeun** [comment]
Acho alterações justas. Está na fila de alterações
