### ISSUE TITLE
Extensão para VSCode

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [eguatech/egua#120]
Issue apenas para marcar que estou trabalhando em uma extensão para o VSCode.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva qualquer suporte que você precisar é só chamar!

**Comment by leonelsanchesdasilva** [comment]
https://github.com/eguatech/egua-extensao-vscode

**Comment by samuelrvg** [comment]
https://marketplace.visualstudio.com/items?itemName=LinguagemEgua.linguagem-egua-vscode&ssr=false#overview
