### ISSUE TITLE
Mais issues do github para o evento hacktoberfest

### ISSUE THREAD

**Issue by RenatoLopes771** [eguatech/egua#127]
Olá. Acho que seria uma boa os devs estipular algumas issues para o pessoal do hacktoberfest interagir com o projeto.

Pode ser feature request, ou um bug, etc.

**Comment by lucaspompeun** [comment]
Olá, @RenatoLopes771. Tudo bem? O motivo pelo qual a linguagem está "aparentemente" parada é a escrita do meu TCC que será a linguagem. Desde abril tenho me dedicado 100% à escrita dele, por isso a ausência de issues, porém sinta-se convidado a criar issues e enviar PRs, pode ter certeza que irei avaliar com muito carinho :)
