### ISSUE TITLE
Corrigindo exemplos de dicionários

### ISSUE THREAD

**Issue by asafedainez** [eguatech/egua#135]
Na página de tipos de dados, onde descreve dicionários o código não está funcional no IDEGUA.

**Comment by leonelsanchesdasilva** [comment]
@asafedainez Tentei o seguinte:

```
var d = {};
d['a'] = 'b';
escreva(d);
```
Imprimiu: 

```[object Object]```

Seria este o problema?

**Comment by leonelsanchesdasilva** [comment]
https://github.com/eguatech/egua/pull/138
