### ISSUE TITLE
Corrigir import na errado

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#137]
Corrigir import na errado

https://github.com/eguatech/egua/blob/f670c2407d0f7fc2404cfa3323b44ce97b773e77/src/structures/instance.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1

**Comment by leonelsanchesdasilva** [comment]
https://github.com/eguatech/egua/pull/139
