### ISSUE TITLE
Self-hosting?

### ISSUE THREAD

**Issue by Krymancer** [eguatech/egua#150]
Todo o código é em JS (ate onde eu vi), é planejado que algum dia a lang se torne self-hosting?

**Comment by lucaspompeun** [comment]
Tudo é JS e não há planos para a linguagem se tornar self-hosted, pois vai contra o princípio de dispensar instalação para a sua utilização, o que é um dos pilares da linguagem. Caso seja de seu interesse usar a linguagem local no VSCode, é possível baixando o interpretador da linguagem no NPM com `npm i -g egua`, conforme documentação:
![image](https://user-images.githubusercontent.com/8001253/177558871-44d4d0e2-12fd-4a96-9416-c05576e82c60.png)
