### ISSUE TITLE
Ponteiro não condiz com o input de texto

### ISSUE THREAD

**Issue by PedroGXV** [eguatech/egua#156]
# Como reproduzir?

[Clique para assistir a reprocução](https://www.youtube.com/watch?v=4aMwXyRgKU8&ab_channel=PedroXavier)

Reproduzido em Firefox 105.0.3 (Versão Estável) e em Chrome 106.0.5249.119 (Versão Estável).

## Sobre o erro

O ponteiro de entrada do teclado não condiz com a posição correta.

**Comment by lucaspompeun** [comment]
Bug corrigido e já deployado em produção
