### ISSUE TITLE
Sugestão: Usar ferramenta como o EditorConfig para padronizar o código.

### ISSUE THREAD

**Issue by Andre0n** [eguatech/egua#160]
Depois de clonar o repositório em minha máquina, comecei a navegar pelo projeto e notei que alguns arquivos estão com formatações diferentes alguns usam tab outros espaços, alguns com indentação de 2 outros com 4, enfim a sugestão é usar alguma uma ferramenta como o EditorConfig para padronizar a formatação entre os arquivos do projeto.

**Comment by lucaspompeun** [comment]
Boa, obrigado pela recomendação, certamente seguirei!

**Comment by Andre0n** [comment]
Tranquilo!
