### ISSUE TITLE
Bug: É possível declarar funções sem identificador no escopo global.

### ISSUE THREAD

**Issue by Andre0n** [eguatech/egua#162]
No `parse.js`  o método `declaration()` faz o parse de um função sem  nome como um `expressionStatement`não entendi a verificação no primeiro `if`
```js
declaration() {
        try {
            if (
                this.check(tokenTypes.FUNÇÃO) &&
                this.checkNext(tokenTypes.IDENTIFIER)
            ) {
                this.consume(tokenTypes.FUNÇÃO, null);
                return this.function("função");
            }
            if (this.match(tokenTypes.VAR)) return this.varDeclaration();
            if (this.match(tokenTypes.CLASSE)) return this.classDeclaration();

            return this.statement();
        } catch (error) {
            this.synchronize();
            return null;
        }
    }
```

**Comment by lucaspompeun** [comment]
De fato, com isso o erro sai bem genérico como apenas "[Linha: 3] Erro no fim: Esperado ';' após expressão.".
Isso acontece por falta de uma verificação do identifier, o que leva o parser a não identificar um estado específico e leva para um genérico.

**Comment by lucaspompeun** [comment]
Possível local da correção: https://github.com/eguatech/egua/blob/7b3bb09559b5dd68164ee5e5c98f7b7d99edb8e0/src/parser.js#L702

Há também a possibilidade da criação de um functionStatement que irá verificar isso. Ou corrigir de maneira mais direta, fazendo a verificação direto no método 'declaration' e trazendo a mensagem de erro mais clara.

**Comment by Andre0n** [comment]
Fiz o seguinte, apenas removi a verificação do next token ser um `INDENTIFIER`
```js
   declaration() {
        try {
            if (this.check(tokenTypes.FUNÇÃO)) {
                this.consume(tokenTypes.FUNÇÃO, null);
                return this.function("função");
            }
            if (this.match(tokenTypes.VAR)) return this.varDeclaration();
            if (this.match(tokenTypes.CLASSE)) return this.classDeclaration();

            return this.statement();
        } catch (error) {
            this.synchronize();
            return null;
        }
    }
``

**Comment by Andre0n** [comment]
No function já garante o próximo token ser `IDENTIFIER`
```js
function(kind) {
   let name = this.consume(tokenTypes.IDENTIFIER, `Esperado nome ${kind}.`);
   return new Stmt.Função(name, this.functionBody(kind));
}
```

**Comment by lucaspompeun** [comment]
Show, a solução aparenta ser boa e funcional, se quiser fazer um PR, eu já avalio e testo

**Comment by Andre0n** [comment]
Beleza!
