### ISSUE TITLE
Este projeto ainda é mantido?

### ISSUE THREAD

**Issue by hellmrf** [eguatech/egua#176]
Oi, eu sou autor de um [curso gratuito no Youtube de Portugol Studio](https://youtu.be/6OIADpFImtc?feature=shared) com centenas de milhares de visualizações. Vou produzir um novo curso sobre alguma outra linguagem em português, e estou considerando Égua.

Este projeto ainda está sendo mantido?

**Comment by lucaspompeun** [comment]
Olá @hellmrf 
O projeto ainda é mantido sim! Está a todo vapor e cada vez mais com novas pessoas conhecendo. Fico muito feliz em saber que você tem interesse em ensinar égua. caso precise de algum auxílio pode contar comigo.

**Comment by hellmrf** [comment]
Que bom saber disso! Vou fechar esta issue por enquanto, e retorno se precisar de algo. Obrigado pela disposição e pelo projeto!
