### ISSUE TITLE
Atualizar para download em windows

### ISSUE THREAD

**Issue by caue-alves** [eguatech/egua#3]
Olá, tive interesse em usar a linguagem localmente, mas não posso pois uso o Windows, eu sei que demora e que não é simples assim, mas seria possível desenvolver uma versão para Windows, agredeço.

**Comment by lucaspompeun** [comment]
Olá @caue-alves. Em relação a versão local não temos nada planejado em relação a isso, pois o foco da linguagem não é rodar localmente, mas sim via navegador de internet. Fornecer uma versão local para windows  implica na necessidade de oferecer suporte a esta versão, já que não faria sentido oferecer um uso precário no ambiente local. A utilização na web é de extrema leveza, portanto mesmo com problemas de conexão com a internet você ainda consegue acessar a IDEgua via https://egua.tech/egua
Nossos testes mostram que conexões com velocidade baixa de 1Mb são capazes de carregar o egua sem grandes problemas. Uma possível solução para seu problema poderia ser fazer o download do repositório via ZIP, extrair no seu computador e acessar o arquivo index.html, assim ele abrirá em seu navegador, mas sem a necessidade de internet. Fica ligado nas redes sociais da linguagem, que estão no README deste repositório, e se em algum momento a gente tiver uma versão local, você vai ficar sabendo :)
![image](https://user-images.githubusercontent.com/8001253/91322359-04cee500-e796-11ea-8577-5145666e9ebf.png)

**Comment by caue-alves** [comment]
Obrigado, realmente a necessidade e muito pequena comparada o trabalho que isso daria, ficarei ligado nas redes sociais, obrigado.

**Comment by joseflaviojr** [comment]
Olá, pessoal!

Tem uma forma de fazer rodar o Égua nativamente no Windows, sem muito trabalho.
O [Ipê-roxo](https://github.com/joseflaviojr/iperoxo) tem camada front-end baseada em JavaScript e compila hibridamente para sistema nativo através de [Cordova + Electron](https://cordova.apache.org/docs/en/latest/guide/platforms/electron/index.html).

É basicamente pegar o `index.html` do Égua e ajustá-lo conforme o `index.html` do Ipê-roxo. O restante fica por conta do framework. Aqui tem um manual que ensino a compilar para Android: [https://github.com/joseflaviojr/iperoxo/tree/master/iperoxo-cordova](https://github.com/joseflaviojr/iperoxo/tree/master/iperoxo-cordova)

Exemplo de aplicativo móvel feito dessa forma: [https://play.google.com/store/apps/details?id=br.edu.ifpa.praesentia](https://play.google.com/store/apps/details?id=br.edu.ifpa.praesentia)
