### ISSUE TITLE
Erro ao passar função como parâmetro

### ISSUE THREAD

**Issue by barbozafernando** [eguatech/egua#38]
Olá, tomei liberdade de criar o método `mapear`, cuja função é a mesma do `Array.map()` do Javascript. Porém, estou com um problema.

![err](https://user-images.githubusercontent.com/45888984/104114171-1c8bad80-52e0-11eb-9ab0-9d374c5d45c2.png)

A linguagem não permite que uma função receba outra função como parâmetro.
Alguém poderia me guiar nesse trecho ou corrigir pra poder dar pull?

Valeu!

**Comment by barbozafernando** [comment]
Bom, testando algumas coisas aqui, percebi um detalhe. No exemplo acima, como função de callback, eu chamo `function` ao invés de `funcao`. Ao corrigir isso, me deparo com os seguintes erros.

![err](https://user-images.githubusercontent.com/45888984/104241751-ea439280-543c-11eb-9ab9-bb46bc85bded.png)

**Comment by lucaspompeun** [comment]
Boa noite @barbozafernando . Mais uma vez eu agradeço imensamente o interesse por nos ajudar no desenvolvimento da linguagem, peço desculpas pela demora também, eu estava fazendo alguns code reviews no código atual e acabei demorando mais do que esperava.

Vamos lá.
Vi que você falou sobre código duplicado no arquivo `dist.js` e esse arquivo é o arquivo gerado automaticamente pela build para web via Browserify, por isso os códigos sempre estarão duplicados, já que o código fonte do interpretador é via Node.JS e o navegador não aceita código escrito apenas para o node sem um tratamento prévio.

Em relação a função mapear, ela ainda não existe na linguagem, então nativamente não ée possível chamá-la. Você está desenvolvendo ela? Caso positivo, acredito que o melhor jeito é construir no modelo de função interna, pois sinceramente desconheço uma maneira de fazer função aceitar função como argumento via interpretador. Há também um erro em `var novoArray = mapear(array, funcao(item){ return item * 2 });`, falta o ; ao final do retorna, ficaria `var novoArray = mapear(array, funcao(item){ retorna item * 2; });`

**Comment by barbozafernando** [comment]
Boa noite, @lucaspompeun.

Em relação a demora, fique tranquilo. Eu percebi que você estava ocupado com outras coisas e etc. Sem problema!

Sim, em relação ao `dist.js` eu acabei percebendo depois hahahaha, my bad!

Ah ta, entendi. Desculpa, cara. Na verdade, eu achei que já estava criando ela na forma de função interna. Peço desculpas.
Em relação ao erro do `;` eu acabei percebendo depois, obrigado!

Mas sim, Lucas, estou desenvolvendo a função `mapear`. E, peço desculpas por não conhecer tanto do projeto ainda, pois as únicas coisas que sei, foram através do seu vídeo postado no youtube ao um tempo atrás. 
Bem, tem como você me dar um pequeno auxílio me dizendo aonde posso criar a função de forma nativa da linguagem? Pois como disse, eu achei que já estava criando a mesma de forma interna.

**Comment by lucaspompeun** [comment]
As funções internas são feitas no arquivo `egua/src/lib/globalLib.js`

**Comment by barbozafernando** [comment]
Foi o que pensei. Criei justamente lá mesmo.

O problema agora, é que o interpretador entende que o `funcao` é um objeto, e não uma função de fato.

![err](https://user-images.githubusercontent.com/45888984/104253063-5e3c6580-5452-11eb-822a-8fc4a8b46528.png)

**Comment by lucaspompeun** [comment]
E pra testar na interface IDEgua não esquece de dar o `npm run build-web`

**Comment by barbozafernando** [comment]
Cara, não to conseguindo fazer executar a função de callback. Tem alguma ideia aí?

Outra coisa, não consigo testar o método pelo terminal porque da esse erro.
![Screenshot_1](https://user-images.githubusercontent.com/45888984/104257465-4b2e9300-545c-11eb-8086-b7ec930eb34a.png)

E pela interface do Égua, não aparece nada. Eu acho que a função de callback não tá sendo executada, por isso não loga nada.

**Comment by lucaspompeun** [comment]
Tentei a solução:
```js
globals.defineVar(
    "mapear",
    new StandardFn(1, function(vetor, funcao){
      return vetor.map(function(){
        return funcao;
      });
    })
  )
```
Entretanto o interpretador da linguagem não permite a passagem de uma expressão segunda expressão para executar na função interna.

![image](https://user-images.githubusercontent.com/8001253/104385706-7d023100-5512-11eb-9652-0f1abe3b70fc.png)

Por enquanto não consigo pensar em uma solução em termos de interpretador para isso :/

**Comment by barbozafernando** [comment]
Aproveitando a sua boa vontade, @leonelsanchesdasilva, hahaha, teria alguma dica pra esse caso aqui?

**Comment by leonelsanchesdasilva** [comment]
@barbozafernando Tenho sim. 

`mapear([5, 3], a * 2)` não vai funcionar porque o interpretador vai avaliar `a * 2` na resolução do argumento. Neste caso, você precisa declarar uma `funcao` primeiro.

```
egua> var f = funcao(a) { retorna a * 2; };
```

Aí implementei sua versão de "mapear" e tive o seguinte:

![image](https://user-images.githubusercontent.com/53848829/107156118-3c3ee180-6931-11eb-9c9f-c2fecf0a104e.png)

Não resolve a tipagem como "function". Resolve como "object". Mais precisamente, uma `EguaFunction`. 

Primeiro sua função tem que aceitar uma `EguaFunction` e aí usar essa `EguaFunction` durante a execução. Acredito que a mistura entre Egua e JavaScript esteja atrapalhando um pouco aqui.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva o que você sugere para que uma `EguaFunction` seja capaz de atender esse tipo de função interna?

**Comment by barbozafernando** [comment]
> @leonelsanchesdasilva o que você sugere para que uma `EguaFunction` seja capaz de atender esse tipo de função interna?

No momento, esse é o único empecilho. Tentei de várias formas, porém sem sucesso.

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun @barbozafernando Bom, `callback` é uma classe, então tem um constructor:

![image](https://user-images.githubusercontent.com/53848829/107728369-b90beb80-6ca2-11eb-9c0d-47e591efe068.png)

Então implementei assim:

```
  globals.defineVar(
    "mapear",
    new StandardFn(1, function (array, callback) {
      if (!Array.isArray(array)) {
        throw new RuntimeError(
          this.token,
          "Parâmetro inválido. O primeiro parâmetro da função, deve ser um array."
        );
      }

      if (callback.constructor.name !== 'EguaFunction') {
        throw new RuntimeError(
          this.token,
          "Parâmetro inválido. O segundo parâmetro da função, deve ser uma função."
        );
      }

      let provisorio = [];
      for (let index = 0; index < array.length; ++index) {
        provisorio.push(
          callback(
            array[index], index, array
          )
        );
      }

      return provisorio;
    })
  );
```

Só que tem outro problema: `callback` é chamado como função normal do JavaScript. `callback` não é uma função do JavaScript. De novo, é uma `EguaFunction`. Chamando do jeito em que está, temos este erro:

```
egua> mapear([5, 3], f);
Waiting for the debugger to disconnect...
readline.js:1170
            throw err;
            ^

TypeError: Cannot read property 'line' of undefined
    at Egua.runtimeError (D:\GitHub\egua\src\egua.js:90:32)
    at Interpreter.interpret (D:\GitHub\egua\src\interpreter.js:779:23)
    at Egua.run (D:\GitHub\egua\src\egua.js:65:21)
    at Interface.<anonymous> (D:\GitHub\egua\src\egua.js:33:18)
    at Interface.emit (events.js:311:20)
    at Interface._onLine (readline.js:322:10)
    at Interface._line (readline.js:699:8)
    at Interface._ttyWrite (readline.js:1025:14)
    at ReadStream.onkeypress (readline.js:198:10)
    at ReadStream.emit (events.js:311:20)
```

Ainda que eu simplesmente troque a chamada de `callback` por `callback.call()`, eu teria outro problema. O primeiro argumento de `callback.call()` precisa ser uma instância de `interpreter` para executar corretamente. `interpreter` não existe dentro de `globalLib` por este motivo (`src\interpreter.js`):

```
module.exports = class Interpreter {
    constructor(Egua, baseDir) {
        this.Egua = Egua;
        this.baseDir = baseDir;

        this.globals = new Environment();
        this.environment = this.globals;
        this.locals = new Map();

        this.globals = loadGlobalLib(this.globals);
    }
```

É uma construção bastante esquisita de objeto, devo dizer. `globals` e `Environment` são a mesma coisa, então deveria prevalecer apenas o nome `environment`, evitando certa confusão e problemas de legibilidade. 

Enfim, o interpretador inicializa o ambiente (`Environment`, ou `globals`), mas a referência do interpretador, que deveria ser passada para a função `globalLib` não está sendo passada. 

Então o que posso fazer é modificar o interpretador para inicializar as funções globais assim:

```
module.exports = class Interpreter {
    constructor(Egua, baseDir) {
        this.Egua = Egua;
        this.baseDir = baseDir;

        this.globals = new Environment();
        this.environment = this.globals;
        this.locals = new Map();

        this.globals = loadGlobalLib(this, this.globals); // Passo o próprio interpretador para dentro da função que 
                                                                                   // inicializa as funções globais.
    }
```

E aí mudo a função que inicializa as funções globais para:

```
module.exports = function (interpreter, globals) { ...
```

Agora tenho o interpretador onde preciso, no caso, na chamada do `callback`. A forma correta de chamar `callback` fica assim:

```
      let provisorio = [];
      for (let index = 0; index < array.length; ++index) {
        interpreter.locals.set(callback.declaration.params[0].name.lexeme, array[index]);
        provisorio.push(
          callback.call(
            interpreter, [array[index]]
          )
        );
      }
```

Por fim, temos:

```
Console da Linguagem Egua v1.1.0

egua> var f = funcao(a) { retorna a * 2; };

egua> escreva(mapear([5, 3], f));
[ 10, 6 ]

egua>
```

Eu posso abrir uma PR, se for o caso.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva eu ficaria extremamente feliz com um PR seu, que solução genial.
