### ISSUE TITLE
Adiciona tratamento do tipo de dado de entrada

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#39]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L1014-L1018

**Comment by barbozafernando** [comment]
Boa noite, @lucaspompeun. Caso permita, posso lhe ajudar em algumas dessas issues. Caso positivo, vou resolvê-las em uma branch separada, logo, teria algum padrão de nomeação de branch ou commits pra usar no projeto?

**Comment by lucaspompeun** [comment]
Opa, @barbozafernando.
Fico feliz com isso. Sua ajuda seria incrível. Os padrões de commit consistem apenas em por # e o número da Issue que ele se refere, se for caso. Em termos de branch, não temos padrão de nome, você pode fazer um fork, criar sua branch e efetuar um PR para a nossa branch de desenvolvimento. Lá o código será atualizado para o ambiente de desenvolvimento que temos na Azure, sob o link https://blue-meadow-0f18a2410.azurestaticapps.net/ (ainda não adicionei no guia de contribuição, pois o ambiente foi feito essa semana, então é novidade pra todos haha)
Nesse ambiente será possível fazer testes e verificar possíveis erros que evitamos na produção.

Qualquer dúvida e/ou problemas é só me marcar que a gente vai se acertando. Vão ser um enorme prazer ter sua ajuda.
