### ISSUE TITLE
Métodos para ordenação

### ISSUE THREAD

**Issue by Natalie9** [eguatech/egua#4]
Pessoal, já existe alguma lib matemática com métodos de ordenação como o sort?

**Comment by lucaspompeun** [comment]
Olá, @Natalie9. Ainda não temos nada deste tipo implementado, mas esta issue será utilizada para implementação deste método em breve. Caso você queira trabalhar numa possível implementação, temos um vídeo falando sobre como criar bibliotecas e métodos na linguagem: https://youtu.be/CZw0-y4Em2U

**Comment by Natalie9** [comment]
Bacana, quero sim contribuir, vou acessar material e em assim que possível contatar a equipe para validação. Obrigada pela resposta :)

**Comment by GCrispino** [comment]
Olá!

Eu estaria interessado em contribuir. Existe alguma(s) funcionalidade(s) que vocês tem como prioridade em adicionar à linguagem?
Seguindo o caso da @Natalie9 de funções de ordenação, e pensando em uma possível biblioteca com métodos para vetores (métodos como sort, find, map, filter): existe alguma indicação de como isso seria feito? Por exemplo, seria uma biblioteca padrão da linguagem (me parece a melhor opção), como a biblioteca "time" (com algum nome tipo "vetor" ou algo melhor), ou seria um pacote separado, como a EguaMAT?

**Comment by lucaspompeun** [comment]
Olá, pessoal.

Nosso time de desenvolvimento implementou essa funcionalidade sob o comando do @BrennusCaio, então hoje temos o seguinte;

```js
//Vetor de strings
var vetorNomes = ["Lucas", "Heictor", "Julio", "Brennus", "Arleson"];
//Vetor de números
var vetorNumeros = [1, 2, 6, 7, 3, 4];

vetorNomes = ordenar(vetorNomes);
escreva(vetorNomes);
//saída: Arleson,Brennus,Heictor,Julio,Lucas

vetorNumeros = ordenar(vetorNumeros);
escreva(vetorNumeros);
//saída: 1,2,3,4,6,7
```

Agradeço a todos pelas ideias e considerações. xD
