### ISSUE TITLE
Refatorar função para permitir teste e remover console log

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#42]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L959-L978

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun Essas linhas nem existem mais. Acho que pode ser fechado.

**Comment by lucaspompeun** [comment]
Agora essa função foi para a seguinte linha:

https://github.com/eguatech/egua/blob/a8fb8867ef9c70b1bcf2e7c45282f5d1e0050f2d/src/lib/eguamat.js#L881-L900

Obrigado pela sinalização @leonelsanchesdasilva
