### ISSUE TITLE
Remover console.log

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#44]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L934

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun Essa linha nem existe mais. Acho que pode ser fechado.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva irei fechar essa issue, por algum motivo só marquei o erro isolado, longe de um contexto
