### ISSUE TITLE
Remover função "mrufh"

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#47]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L865-L881

**Comment by barbozafernando** [comment]
Boa tarde, @lucaspompeun, essa função deve retornar apenas o resultado, correto?

**Comment by lucaspompeun** [comment]
@Heictor Dá uma verificada nessa dúvida do @barbozafernando pra dar o melhor direcionamento pra ele

**Comment by lucaspompeun** [comment]
@barbozafernando eai, cara. Blz?
Então, pra evitar problemas e acabar com todas as dúvidas, decidi que vamos remover essa função.
