### ISSUE TITLE
Refatorar verificação de parâmetros , já que a função verifica apenas se o primeiro foi fornecido

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#48]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L855-L863

**Comment by barbozafernando** [comment]
Boa noite, @lucaspompeun. Estou refatorando essa função e cai em um detalhe.

Ao fazer `mat.aceleracao(10, 0, 20, 0))` ele retorna `0.6666666666`. Pra formatar a quantidade de casas decimais, geralmente se usa o `toFixed()`. Porém, ele arredonda caso o número seja decimal. A dúvida é, há algum problema caso arredonde? Se sim, posso retornar o número inteiro ou posso transformá-lo em string e pegar apenas os 3 primeiros caracteres. Caso não, deixo assim mesmo.

**Comment by lucaspompeun** [comment]
Boa noite, @barbozafernando. Tudo certo?
Acredito que não há problema em ter um resultado com várias casas decimais, acho que o trabalho de fazer esse tratamento de arredondamento pode e deve ser feito pelo usuário, já que a biblioteca possui uma função chamada "aprox" que efetua o arredondamento. 
O retorno da função deve ser numérico.
