### ISSUE TITLE
Remover função da biblioteca eguamat e passar para função interna

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#52]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L804-L806

**Comment by barbozafernando** [comment]
O que acha de criar dois métodos de números aleatórios? Um seria o `aleatorio()` que retornaria qualquer número e o outro, sei lá, `aleatorioEntre(min, max)` que retornaria um número aleatório dentro do "range" que o usuário passou por parâmetro.

**Comment by lucaspompeun** [comment]
@barbozafernando eu acho genial. Você acha que isso fica melhor na biblioteca eguamat ou como função interna da linguagem?

**Comment by barbozafernando** [comment]
Cara, acho que como função interna ficaria melhor.

**Comment by lucaspompeun** [comment]
Nome da issue alterado

**Comment by barbozafernando** [comment]
Pompeu, uma dúvida. O arquivo de testes são só testes da `eguamat`?
