### ISSUE TITLE
Remover função eguamat.matriz();

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#57]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L511-L551

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun Se bem entendi o que essa função faz, é pegar uma matriz natural e transformar em uma tabela no editor. 

Se for isso, essa função nem deveria estar aí, e sim numa biblioteca de visualização em separado.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva em que tipo de biblioteca você sugere? A ideia do eguamat é envolver qualquer coisa relacionada a matemática, por isso essa função existe aqui atualmente

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun Sei que muita gente que está aprendendo Egua não usa o console, mas em console essa função nem funciona, porque `document` nem é definido no Node. 

Essa função deveria ser parte de uma biblioteca exclusiva para a IDEgua. Acho que manter tudo numa biblioteca só (funções matemáticas + plotagem) vai fazer pouco sentido à medida que a linguagem e as bibliotecas crescem. 

O que eu faria: uma outra biblioteca, digamos, `ideagua-matematica`. Pode ser outro nome. É só uma ideia.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva o que vc acha da possibilidade de removemos essa função então? A parte de plotagem eu costume deixar pro console interativo do eguamat, dá uma conferida no repositório eguamat, lá ela já está implementada. Lá o ambiente é mais preparado para visualização.

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun Sou favorável a remover daqui, então.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva certo, faremos isso. Irei alterar o nome da issue.
