### ISSUE TITLE
Refatorar função eguamat.media()

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#68]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L343-L351

**Comment by barbozafernando** [comment]
@lucaspompeun, essa média seria o cálculo de média normal mesmo, né? Tipo, se eu passo 5 valores, somo todos e divido por 5. Seria isso?

**Comment by lucaspompeun** [comment]
@barbozafernando positivo, é isso mesmo. Nesses caso o argumento precisa ser uma lista.

**Comment by barbozafernando** [comment]
Olha, pensei em duas formas de implementar essa função.

- A primeira, é o cara chamando `mat.media()` e passando quantos parâmetros quiser pra fazer a média. Podemos limitar também a quantidade de parâmetros
- A segunda, seria como vc falou. O cara já passar uma lista pra fazer o cálculo.

O que acha, @lucaspompeun ?

**Comment by lucaspompeun** [comment]
Acho perfeito fazer os dois.

**Comment by barbozafernando** [comment]
Mas pensando aqui, Pompeu. Cara, mas será que se fizer dos dois jeitos, não vai dar na mesma? Vou te mostrar o porquê.

```
module.exports.media = function () {
  // Pega cada item que veio por parâmetro e coloca em uma posição em um array.
  const args = [...arguments];

  // Soma todos os itens.
  const valoresSomados = args.reduce((acc, item) => acc + item, 0);

  // Faz o cáculo da média em si e retorna.
  return valoresSomados / args.length;
};
```

Então desse modo, na implementação já colocaria tudo em uma posição do array, então não faria muito sentido permitir o usuário mandar um array de valores ou apenas os valores separados por vírgula, porque no final das contas, vai dar no mesmo.
Pensando assim, o método então receberia apenas os valores que o usuário gostaria de cácular a média e obviamente, todos tem de ser do tipo `número`.

O que acha, @lucaspompeun e @leonelsanchesdasilva ?

**Comment by lucaspompeun** [comment]
> Mas pensando aqui, Pompeu. Cara, mas será que se fizer dos dois jeitos, não vai dar na mesma? Vou te mostrar o porquê.
> 
> ```
> module.exports.media = function () {
>   // Pega cada item que veio por parâmetro e coloca em uma posição diferente em um array.
>   const args = [...arguments];
> 
>   // Soma todos os itens.
>   const valoresSomados = args.reduce((acumulador, itemAtual) => acumulador + itemAtual, 0);
> 
>   // Faz o cáculo da média em si e retorna.
>   return (valoresSomados / args.length);
> };
> ```
> 
> Então desse modo, na implementação já colocaria tudo em um array, então não faria muito sentido permitir o usuário mandar um array de valores ou apenas os valores separados por vírgula, porque no final das contas, vai dar no mesmo.
> Pensando assim, o método então receberia apenas os valores que o usuário gostaria de cácular a média e obviamente, todos tem de ser do tipo `número`.
> 
> O que acham, @lucaspompeun e @leonelsanchesdasilva ?

Eu particularmente gosto que tenha como entrada um vetor pois ajuda o usuário a entender uma das aplicações de vetores. Esse é o motivo pelo qual gosto de ter o vetor como entrada. O que vocês acham?

**Comment by leonelsanchesdasilva** [comment]
> Mas pensando aqui, Pompeu. Cara, mas será que se fizer dos dois jeitos, não vai dar na mesma? Vou te mostrar o porquê.
> 
> ```
> module.exports.media = function () {
>   // Pega cada item que veio por parâmetro e coloca em uma posição diferente em um array.
>   const args = [...arguments];
> 
>   // Soma todos os itens.
>   const valoresSomados = args.reduce((acumulador, itemAtual) => acumulador + itemAtual, 0);
> 
>   // Faz o cáculo da média em si e retorna.
>   return (valoresSomados / args.length);
> };
> ```
> 
> Então desse modo, na implementação já colocaria tudo em um array, então não faria muito sentido permitir o usuário mandar um array de valores ou apenas os valores separados por vírgula, porque no final das contas, vai dar no mesmo.
> Pensando assim, o método então receberia apenas os valores que o usuário gostaria de cácular a média e obviamente, todos tem de ser do tipo `número`.
> 
> O que acham, @lucaspompeun e @leonelsanchesdasilva ?

A implementação considerando número variável de argumentos é possível, mas vai aumentar o tratamento dos argumentos. 

Nada me impediria, por exemplo, de passar uma série indefinida de arrays numéricos, o que já faria o método falhar na hora de fazer a redução. Um `.flat()` de todos os arrays antes teria que ser feito. 

Eu faria `media()` apenas aceitando um vetor único de números. Se houver necessidade de implementar uma versão mais robusta, isso pode ser feito depois.

**Comment by barbozafernando** [comment]
> > Mas pensando aqui, Pompeu. Cara, mas será que se fizer dos dois jeitos, não vai dar na mesma? Vou te mostrar o porquê.
> > ```
> > module.exports.media = function () {
> >   // Pega cada item que veio por parâmetro e coloca em uma posição diferente em um array.
> >   const args = [...arguments];
> > 
> >   // Soma todos os itens.
> >   const valoresSomados = args.reduce((acumulador, itemAtual) => acumulador + itemAtual, 0);
> > 
> >   // Faz o cáculo da média em si e retorna.
> >   return (valoresSomados / args.length);
> > };
> > ```
> > 
> > 
> > Então desse modo, na implementação já colocaria tudo em um array, então não faria muito sentido permitir o usuário mandar um array de valores ou apenas os valores separados por vírgula, porque no final das contas, vai dar no mesmo.
> > Pensando assim, o método então receberia apenas os valores que o usuário gostaria de cácular a média e obviamente, todos tem de ser do tipo `número`.
> > O que acham, @lucaspompeun e @leonelsanchesdasilva ?
> 
> A implementação considerando número variável de argumentos é possível, mas vai aumentar o tratamento dos argumentos.
> 
> Nada me impediria, por exemplo, de passar uma série indefinida de arrays numéricos, o que já faria o método falhar na hora de fazer a redução. Um `.flat()` de todos os arrays antes teria que ser feito.
> 
> Eu faria `media()` apenas aceitando um vetor único de números. Se houver necessidade de implementar uma versão mais robusta, isso pode ser feito depois.

Eu estava fazendo exatamente isso. Estava tentando implementar desse jeito aí, e cara, terei que fazer vários tratamentos dos argumentos. No momento, talvez não seja necessário mesmo. Concordo em aceitar apenas o array. 
O que acha, Pompeu?

**Comment by lucaspompeun** [comment]
Podemos ficar com o argumento único de array.
