### ISSUE TITLE
Novos métodos pra lib de tempo

### ISSUE THREAD

**Issue by barbozafernando** [eguatech/egua#7]
Opa! Curti o seu projeto e quis contribuir com algo, @lucaspompeun. Eu implementei três novos métodos na lib de `time`. Um dos métodos se chama `segundos`, outro é o `minutos` e outro chamado `horas`; eles retornam o segundo, o minuto e a hora atual respectivamente, inclusive, renomeei o método `hora` que já existia para `horario`, porque ele retornava uma data completa, com dia, mês, ano, horário em GMT, dia da semana e etc, sei lá, achei que ficaria mais fácil de entender assim. Caso discorde, altero de boa.

![time](https://user-images.githubusercontent.com/45888984/95029898-0a1b2b80-0682-11eb-827c-7a211622f831.png)

**Comment by lucaspompeun** [comment]
Olá @barbozafernando tudo bom?
Cara, sensacional! Pode mandar seu PR que aceito na hora, tudo está certinho
