### ISSUE TITLE
Refatorar função e alterar nome para "pontosAleatorios"

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#77]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L188-L203

**Comment by leonelsanchesdasilva** [comment]
Podia mudar o nome também, não? `module/exports.pontosAleatorios`, por exemplo.

**Comment by lucaspompeun** [comment]
> Podia mudar o nome também, não? `module/exports.pontosAleatorios`, por exemplo.

Acho uma melhoria muito válida!
