### ISSUE TITLE
Refatorar verificação de parâmetros e remover string do retorno

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#85]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/eguamat.js#L62-L71

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun O que eu entendi dessa função é o seguinte:

- A função recebe dois números, `a` e `b`,
- `a` é a distância entre um ponto da abscissa e outro;
- `b` é o valor central no eixo x;
- O resultado será a geração de 7 pontos no eixo x.

Perguntas:

- Qual a utilidade dessa função? Em que tipo de exercício é usada?
- Por que apenas `a` é verificada?
- Por que o número de pontos gerados não é variável?

Tendo essas respostas, eu posso refatorar essa função também (escolhendo um nome melhor, aliás).

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva essa função foi incluída por outro desenvolvedor e ele acabou por sair do desenvolvimento da linguagem antes mesmo de documentá-la. Você acha que deveríamos removê-la ou tentaremos encontrar de fato uma aplicação à mesma?

**Comment by leonelsanchesdasilva** [comment]
@lucaspompeun Eu faria um trabalho melhor de parâmetros, renomearia para `gerarPontosAbscissa` e faria algo mais dinâmico, com mais ou menos de 7 pontos, mantendo o padrão de 7 pontos.

**Comment by lucaspompeun** [comment]
@leonelsanchesdasilva vou deixar essa decisão com você haha
Você decide se manteremos ou removeremos.
