### ISSUE TITLE
Adicionar verificação de parâmetro na função

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/egua#88]
https://github.com/eguatech/egua/blob/5671a030a7fd3fcef57dbde0846cf5613b25f566/src/lib/time.js#L17-L20

**Comment by barbozafernando** [comment]
Boa noite, @lucaspompeun. O `timestamp` seria uma string com uma data e a função `horario` retornaria um objeto `Date` dessa data enviada. Seria isso?

**Comment by lucaspompeun** [comment]
@barbozafernando isso mesmo
